In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7,8])

In [3]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
b = np.array(([1,2,3,4,5,6],[2,4,6,8,0,2], [2,4,6,8,0,2]))

In [5]:
b

array([[1, 2, 3, 4, 5, 6],
       [2, 4, 6, 8, 0, 2],
       [2, 4, 6, 8, 0, 2]])

In [6]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [7]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [8]:
np.full((2,2), 7)

array([[7, 7],
       [7, 7]])

In [9]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [10]:
c = np.random.random((2,2))

In [11]:
c

array([[0.05769456, 0.02956685],
       [0.19988995, 0.8437513 ]])

In [12]:
a.shape

(8,)

In [13]:
b.shape

(3, 6)

In [14]:
c.shape

(2, 2)

In [15]:
a.ndim

1

In [16]:
b.ndim

2

In [17]:
c.ndim

2

In [18]:
a.size

8

In [19]:
b.size

18

In [20]:
a.dtype.name

'int32'

In [21]:
b.dtype.name

'int32'

In [22]:
c.dtype.name

'float64'

In [23]:
type(a)

numpy.ndarray

In [24]:
b.shape

(3, 6)

In [25]:
np.zeros(b.shape)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [26]:
np.ones(a.shape)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
a[0]

1

In [29]:
b

array([[1, 2, 3, 4, 5, 6],
       [2, 4, 6, 8, 0, 2],
       [2, 4, 6, 8, 0, 2]])

In [30]:
b[0,5]

6

In [31]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
a[0:1]

array([1])

In [33]:
a[:3]

array([1, 2, 3])

In [34]:
b

array([[1, 2, 3, 4, 5, 6],
       [2, 4, 6, 8, 0, 2],
       [2, 4, 6, 8, 0, 2]])

In [35]:
b[:2,1:3]

array([[2, 3],
       [4, 6]])

In [36]:
b[1:2, :]

array([[2, 4, 6, 8, 0, 2]])

In [37]:
b[:,2]

array([3, 6, 6])

In [38]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
b

array([[1, 2, 3, 4, 5, 6],
       [2, 4, 6, 8, 0, 2],
       [2, 4, 6, 8, 0, 2]])

In [40]:
b[0,0] = 7

In [41]:
b

array([[7, 2, 3, 4, 5, 6],
       [2, 4, 6, 8, 0, 2],
       [2, 4, 6, 8, 0, 2]])

In [42]:
d = np.copy(b)

In [43]:
d

array([[7, 2, 3, 4, 5, 6],
       [2, 4, 6, 8, 0, 2],
       [2, 4, 6, 8, 0, 2]])

In [44]:
e = d

In [45]:
e

array([[7, 2, 3, 4, 5, 6],
       [2, 4, 6, 8, 0, 2],
       [2, 4, 6, 8, 0, 2]])

In [46]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
(a>2)

array([False, False,  True,  True,  True,  True,  True,  True])

In [48]:
a[a>2]

array([3, 4, 5, 6, 7, 8])

In [49]:
b

array([[7, 2, 3, 4, 5, 6],
       [2, 4, 6, 8, 0, 2],
       [2, 4, 6, 8, 0, 2]])

In [50]:
b>5

array([[ True, False, False, False, False,  True],
       [False, False,  True,  True, False, False],
       [False, False,  True,  True, False, False]])

In [51]:
b[b>2]

array([7, 3, 4, 5, 6, 4, 6, 8, 4, 6, 8])

In [52]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [53]:
a.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [54]:
a = a.reshape(2,4)

In [55]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [56]:
a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [58]:
a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [65]:
data = np.genfromtxt("diabetes.csv", delimiter = ",")

In [68]:
import pandas as pd

In [69]:
data = pd.read_csv("diabetes.csv")

In [70]:
data = np.array(data)

In [73]:
data.shape

(768, 9)

In [88]:
dataset = np.loadtxt("diabetes.csv", delimiter  = ",", skiprows=1)

In [89]:
dataset.shape

(768, 9)

In [90]:
dataset[0,2]

72.0

In [91]:
dataset[112,7]

23.0

In [92]:
dataset[227,8]

1.0

In [96]:
dataset[dataset[:,8] == 1,].shape

(268, 9)

In [99]:
sum(dataset[:,4] == 0)

374

In [102]:
dataset == 0

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False,  True],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False,  True],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False,  True]])

In [109]:
dataset1 = dataset[:,1:]

In [110]:
dataset.shape

(768, 9)

In [111]:
dataset1.shape

(768, 8)

In [112]:
dataset

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [113]:
dataset1

array([[148.   ,  72.   ,  35.   , ...,   0.627,  50.   ,   1.   ],
       [ 85.   ,  66.   ,  29.   , ...,   0.351,  31.   ,   0.   ],
       [183.   ,  64.   ,   0.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [121.   ,  72.   ,  23.   , ...,   0.245,  30.   ,   0.   ],
       [126.   ,  60.   ,   0.   , ...,   0.349,  47.   ,   1.   ],
       [ 93.   ,  70.   ,  31.   , ...,   0.315,  23.   ,   0.   ]])

In [117]:
dataset1 == 0

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False,  True],
       [False, False,  True, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False,  True],
       [False, False,  True, ..., False, False, False],
       [False, False, False, ..., False, False,  True]])

array([0., 0., 0., ..., 0., 0., 0.])