In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7,8])

In [3]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
b = np.array(([1,2,3,4,5,6],[2,4,6,8,0,2], [2,4,6,8,0,2]))

In [6]:
b

array([[1, 2, 3, 4, 5, 6],
       [2, 4, 6, 8, 0, 2],
       [2, 4, 6, 8, 0, 2]])

In [7]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [9]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [10]:
np.full((2,2), 7)

array([[7, 7],
       [7, 7]])

In [11]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [12]:
c = np.random.random((2,2))

In [13]:
c

array([[0.62882705, 0.82352456],
       [0.86414969, 0.48945435]])

In [14]:
a.shape

(8,)

In [15]:
b.shape

(3, 6)

In [16]:
c.shape

(2, 2)

In [18]:
a.ndim

1

In [19]:
b.ndim

2

In [20]:
c.ndim

2

In [21]:
a.size

8

In [22]:
b.size

18

In [23]:
a.dtype.name

'int32'

In [24]:
b.dtype.name

'int32'

In [25]:
c.dtype.name

'float64'

In [26]:
type(a)

numpy.ndarray

In [27]:
b.shape

(3, 6)

In [28]:
np.zeros(b.shape)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [30]:
np.ones(a.shape)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [31]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
a[0]

1

In [33]:
b

array([[1, 2, 3, 4, 5, 6],
       [2, 4, 6, 8, 0, 2],
       [2, 4, 6, 8, 0, 2]])

In [38]:
b[0,5]

6

In [39]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
a[0:1]

array([1])

In [42]:
a[:3]

array([1, 2, 3])

In [43]:
b

array([[1, 2, 3, 4, 5, 6],
       [2, 4, 6, 8, 0, 2],
       [2, 4, 6, 8, 0, 2]])

In [44]:
b[:2,1:3]

array([[2, 3],
       [4, 6]])

In [47]:
b[1:2, :]

array([[2, 4, 6, 8, 0, 2]])

In [48]:
b[:,2]

array([3, 6, 6])